# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true


## Environment Properties
minecraft_version=1.21.1

minecraft_version_range=[1.21.1,1.22)

# Fabric Properties
# check these on https://fabricmc.net/develop
yarn_mappings=1.21.1+build.3
loader_version=0.16.14
loom_version=1.10-SNAPSHOT
fabric_version=0.116.3+1.21.1



## Mod Properties

mod_id=spudaciousshops

mod_name=Spud's Shops

mod_license=MIT

mod_version=1.10.2-fabric-1.21.1

mod_authors=Spudacious5705

mod_description=A simple and decorative shop mod
