# Mod Loader Configuration
modLoader="javafml"
loaderVersion="${loader_version_range}"

license="MIT"

# Mod Definition
[[mods]]
modId="${mod_id}"
logoFile = "shops_logo.png"
logoBlur = false
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description="${mod_description}"

# Dependencies
[[dependencies."${mod_id}"]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

